/**
 * Generates the Flyway dev-data migration from the apps' own seed (packages/shared/src/seed.ts),
 * so the backend demo matches the mock exactly — same ids, names, bookings, reviews and logins.
 *
 * Dates in seed.ts are relative to "now". The SQL keeps them relative: timestamps become
 * `now() - interval '…'` and booking dates `current IST date + n`, so the demo stays fresh
 * whenever the migration runs.
 *
 *   npm run backend:seed   (from the repo root)
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { CITY_CENTRES } from '../../packages/shared/src/geo';
import { toISODate } from '../../packages/shared/src/format';
import { createSeedDatabase, DEMO } from '../../packages/shared/src/seed';
import type { Booking } from '../../packages/shared/src/types';

const NOW = new Date();
const db = createSeedDatabase(NOW);
const out: string[] = [];

const q = (v: unknown): string => {
  if (v === undefined || v === null) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return `'${String(v).replace(/'/g, "''")}'`;
};
/** A seed timestamp as an offset from the moment the migration runs. */
const ts = (iso: string | undefined): string => {
  if (!iso) return 'NULL';
  const secs = Math.round((NOW.getTime() - new Date(iso).getTime()) / 1000);
  return secs >= 0 ? `now() - interval '${secs} seconds'` : `now() + interval '${-secs} seconds'`;
};
const today = toISODate(NOW);
const dayDiff = (iso: string) => Math.round((Date.parse(`${iso}T00:00:00Z`) - Date.parse(`${today}T00:00:00Z`)) / 86_400_000);
const date = (iso: string): string => `((now() at time zone 'Asia/Kolkata')::date + ${dayDiff(iso)})`;
const insert = (table: string, cols: string[], rows: string[][]) => {
  if (!rows.length) return;
  out.push(`INSERT INTO ${table} (${cols.join(', ')}) VALUES\n${rows.map((r) => `  (${r.join(', ')})`).join(',\n')};\n`);
};

out.push(`-- GENERATED by backend/scripts/generate-dev-seed.ts from packages/shared/src/seed.ts — do not edit by hand.
-- Demo logins: customer ${DEMO.customerPhone}, vendors ${DEMO.vendorPhone} / ${DEMO.pendingVendorPhone} (OTP 123456 in sandbox),
-- admin ${DEMO.adminEmail} / ${DEMO.adminPassword} (also ops@, finance@, support@).
`);

const s = db.settings;
insert('platform_settings', ['id', 'tax_rate', 'default_commission_rate', 'default_inspection_fee', 'whatsapp_number', 'support_phone'],
  [['1', q(s.taxRate), q(s.defaultCommissionRate), q(s.defaultInspectionFee), q(s.whatsappNumber), q(s.supportPhone)]]);
insert('platform_cities', ['name', 'position', 'lat', 'lng'],
  s.cities.map((c, i) => [q(c), q(i), q(CITY_CENTRES[c]?.lat), q(CITY_CENTRES[c]?.lng)]));

insert('service_categories', ['id', 'name', 'tagline', 'description', 'icon', 'image', 'tint', 'enabled', 'popular', 'commission_rate', 'inspection_fee', 'sort_order'],
  db.categories.map((c) => [q(c.id), q(c.name), q(c.tagline), q(c.description), q(c.icon), q(c.image), q(c.tint), q(c.enabled), q(c.popular), q(c.commissionRate), q(c.inspectionFee), q(c.sortOrder)]));
insert('category_includes', ['category_id', 'position', 'text'], db.categories.flatMap((c) => c.includes.map((t, i) => [q(c.id), q(i), q(t)])));
insert('problem_types', ['id', 'category_id', 'name', 'description', 'icon', 'price', 'pricing_model', 'duration_mins', 'enabled'],
  db.problemTypes.map((p) => [q(p.id), q(p.categoryId), q(p.name), q(p.description), q(p.icon), q(p.price), q(p.pricingModel), q(p.durationMins), q(p.enabled)]));

insert('customers', ['id', 'name', 'phone', 'email', 'city', 'blocked', 'created_at'],
  db.customers.map((c) => [q(c.id), q(c.name), q(c.phone), q(c.email), q(c.city), q(c.blocked), ts(c.createdAt)]));
insert('customer_addresses', ['id', 'customer_id', 'label', 'line', 'landmark', 'city', 'pincode', 'lat', 'lng', 'position'],
  db.customers.flatMap((c) => c.addresses.map((a, i) => [q(a.id), q(c.id), q(a.label), q(a.line), q(a.landmark), q(a.city), q(a.pincode), q(a.lat), q(a.lng), q(i)])));

insert('vendors', ['id', 'name', 'phone', 'email', 'photo', 'city', 'status', 'available', 'rating', 'rating_count', 'jobs_completed', 'lat', 'lng', 'joined_at', 'kyc_submitted_at', 'rejection_reason'],
  db.vendors.map((v) => [q(v.id), q(v.name), q(v.phone), q(v.email), q(v.photo), q(v.city), q(v.status), q(v.available), q(v.rating), q(v.ratingCount), q(v.jobsCompleted),
    q(v.location.lat), q(v.location.lng), ts(v.joinedAt), ts(v.kycSubmittedAt), q(v.rejectionReason)]));
insert('vendor_categories', ['vendor_id', 'position', 'category_id'], db.vendors.flatMap((v) => v.categoryIds.map((c, i) => [q(v.id), q(i), q(c)])));
insert('vendor_service_areas', ['vendor_id', 'position', 'area'], db.vendors.flatMap((v) => v.serviceAreas.map((a, i) => [q(v.id), q(i), q(a)])));
insert('vendor_working_hours', ['vendor_id', 'start_time', 'end_time', 'days'],
  db.vendors.map((v) => [q(v.id), q(v.workingHours.start), q(v.workingHours.end), q(v.workingHours.days.join(','))]));
insert('vendor_kyc_documents', ['vendor_id', 'type', 'number', 'image_key', 'status', 'note', 'uploaded_at'],
  db.vendors.flatMap((v) => v.kyc.map((k) => [q(v.id), q(k.type), q(k.number), q(k.imageUri), q(k.status), q(k.note), ts(k.uploadedAt)])));
insert('vendor_bank_accounts', ['vendor_id', 'holder_name', 'account_last4', 'ifsc', 'bank_name'],
  db.vendors.filter((v) => v.bank).map((v) => [q(v.id), q(v.bank!.holderName), q(v.bank!.accountLast4), q(v.bank!.ifsc), q(v.bank!.bankName)]));

// Every seeded admin shares the demo password; stored as a bcrypt hash (pgcrypto, Spring-compatible).
insert('admin_users', ['id', 'name', 'email', 'role', 'password_hash'],
  db.admins.map((a) => [q(a.id), q(a.name), q(a.email), q(a.role), `crypt(${q(DEMO.adminPassword)}, gen_salt('bf', 10))`]));

const bookings = [...db.bookings].reverse();
insert('bookings', ['id', 'code', 'customer_id', 'customer_name', 'customer_phone', 'category_id', 'problem_type_id', 'date', 'slot', 'address_id', 'address_label',
  'address_line', 'address_landmark', 'address_city', 'address_pincode', 'address_lat', 'address_lng', 'notes', 'status', 'vendor_id', 'service_amount', 'tax', 'total',
  'commission_rate', 'commission', 'vendor_payout', 'payment_method', 'payment_status', 'paid_at', 'txn_id', 'failure_reason', 'cancel_reason', 'review_id', 'created_at'],
  bookings.map((b) => [q(b.id), q(b.code), q(b.customerId), q(b.customerName), q(b.customerPhone), q(b.categoryId), q(b.problemTypeId), date(b.date), q(b.slot),
    q(b.address.id), q(b.address.label), q(b.address.line), q(b.address.landmark), q(b.address.city), q(b.address.pincode), q(b.address.lat), q(b.address.lng),
    q(b.notes), q(b.status), q(b.vendorId), q(b.price.serviceAmount), q(b.price.tax), q(b.price.total), q(b.price.commissionRate), q(b.price.commission),
    q(b.price.vendorPayout), q(b.payment.method), q(b.payment.status), ts(b.payment.paidAt), q(b.payment.txnId), q(b.payment.failureReason), q(b.cancelReason),
    q(b.reviewId), ts(b.createdAt)]));
// Seeded bookings carry one problem; store it as an item too, like cart bookings.
const items = (b: Booking) => b.items?.length ? b.items : b.problemTypeId ? [{ problemTypeId: b.problemTypeId, ...pick(b.problemTypeId) }] : [];
const pick = (id: string) => {
  const p = db.problemTypes.find((x) => x.id === id)!;
  return { name: p.name, price: p.price };
};
insert('booking_items', ['booking_id', 'position', 'problem_type_id', 'name', 'price'],
  bookings.flatMap((b) => items(b).map((it, i) => [q(b.id), q(i), q(it.problemTypeId), q(it.name), q(it.price)])));
insert('booking_events', ['booking_id', 'position', 'kind', 'at', 'by_role', 'note'],
  bookings.flatMap((b) => b.timeline.map((e, i) => [q(b.id), q(i), q(e.kind), ts(e.at), q(e.by), q(e.note)])));

const withInspection = bookings.filter((b) => b.inspection);
insert('booking_inspections', ['booking_id', 'description', 'fee', 'status', 'awaiting_customer', 'no_work_note', 'quote_amount', 'quote_note', 'quote_vendor_id',
  'quote_created_at', 'quote_responded_at', 'quote_responded_by'],
  withInspection.map((b) => {
    const i = b.inspection!;
    return [q(b.id), q(i.description), q(i.fee), q(i.status), q(i.awaitingCustomer), q(i.noWorkNote), q(i.quote?.amount), q(i.quote?.note), q(i.quote?.vendorId),
      ts(i.quote?.createdAt), ts(i.quote?.respondedAt), q(i.quote?.respondedBy)];
  }));
insert('inspection_quote_lines', ['booking_id', 'position', 'description', 'amount'],
  withInspection.flatMap((b) => (b.inspection!.quote?.lines ?? []).map((l, i) => [q(b.id), q(i), q(l.description), q(l.amount)])));
insert('inspection_messages', ['id', 'booking_id', 'position', 'from_role', 'author_name', 'text', 'at'],
  withInspection.flatMap((b) => b.inspection!.messages.map((m, i) => [q(m.id), q(b.id), q(i), q(m.from), q(m.authorName), q(m.text), ts(m.at)])));

insert('reviews', ['id', 'booking_id', 'customer_id', 'customer_name', 'vendor_id', 'category_id', 'rating', 'text', 'status', 'created_at'],
  db.reviews.map((r) => [q(r.id), q(r.bookingId), q(r.customerId), q(r.customerName), q(r.vendorId), q(r.categoryId), q(r.rating), q(r.text), q(r.status), ts(r.createdAt)]));
insert('complaints', ['id', 'booking_id', 'customer_id', 'vendor_id', 'subject', 'message', 'status', 'resolution', 'created_at'],
  db.complaints.map((c) => [q(c.id), q(c.bookingId), q(c.customerId), q(c.vendorId), q(c.subject), q(c.message), q(c.status), q(c.resolution), ts(c.createdAt)]));
insert('payouts', ['id', 'vendor_id', 'amount', 'status', 'utr', 'created_at', 'settled_at'],
  db.payouts.map((p) => [q(p.id), q(p.vendorId), q(p.amount), q(p.status), q(p.utr), ts(p.createdAt), ts(p.settledAt)]));
insert('payout_bookings', ['payout_id', 'position', 'booking_id'], db.payouts.flatMap((p) => p.bookingIds.map((id, i) => [q(p.id), q(i), q(id)])));

// Ledger rows for paid bookings and settled payouts, as the payment flow would have written them.
const ledger: string[][] = [];
for (const b of bookings.filter((x) => x.payment.status === 'paid')) {
  const at = ts(b.payment.paidAt ?? b.createdAt);
  ledger.push([q('customer_payment'), q(b.id), q(b.vendorId), 'NULL', q(b.price.total), at]);
  if (b.payment.method === 'cash') ledger.push([q('cash_commission_due'), q(b.id), q(b.vendorId), 'NULL', q(b.price.commission), at]);
  else {
    ledger.push([q('platform_commission'), q(b.id), q(b.vendorId), 'NULL', q(b.price.commission), at]);
    if (b.vendorId) ledger.push([q('vendor_earning'), q(b.id), q(b.vendorId), 'NULL', q(b.price.vendorPayout), at]);
  }
}
for (const p of db.payouts.filter((x) => x.status === 'settled')) ledger.push([q('payout_settled'), 'NULL', q(p.vendorId), q(p.id), q(p.amount), ts(p.settledAt)]);
insert('ledger_entries', ['kind', 'booking_id', 'vendor_id', 'payout_id', 'amount', 'created_at'], ledger);

insert('notifications', ['id', 'audience', 'recipient_id', 'kind', 'title', 'body', 'channels', 'booking_id', 'whatsapp_url', 'read', 'created_at'],
  db.notifications.map((n) => [q(n.id), q(n.audience), q(n.recipientId), q(n.kind), q(n.title), q(n.body), q(n.channels.join(',')), q(n.bookingId), q(n.whatsappUrl), q(n.read), ts(n.createdAt)]));

const target = resolve(__dirname, '../src/main/resources/db/dev/V1000__dev_seed.sql');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out.join('\n'));
console.log(`Wrote ${target} — ${db.bookings.length} bookings, ${db.customers.length} customers, ${db.vendors.length} vendors.`);
